services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    container_name: ourday-app
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - ..env.production
    depends_on:
      - db
    volumes:
      - ./uploads:/app/uploads
      - ./tempUploads:/app/tempUploads

  nginx:
    image: nginx:latest
    container_name: ourday-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./uploads:/app/uploads
      - ./tempUploads:/app/tempUploads
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - app
