version: "3.9"

services:
  app:
    build: .
    container_name: ourday-app
    ports:
      - "8080:8080"
    env_file:
      - .env.docker
    depends_on:
      - db
    volumes:
      - ./uploads:/app/uploads
      - ./tempUploads:/app/tempUploads
    restart: unless-stopped

  db:
    container_name: ourday-db
    image: mariadb:10.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ourday
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
    restart: unless-stopped

volumes:
  db_data:
