services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    container_name: ourday-app
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - ../../.env.production
    depends_on:
      - db
    volumes:
      - ./uploads:/app/uploads
      - ./tempUploads:/app/tempUploads